// Centralized configuration for Débarras Aurea

export const siteConfig = {
  name: "Débarras Aurea",
  description:
    "Service professionnel de débarras et déménagement en Île-de-France. Intervention rapide sous 24 à 48 h, tri et recyclage, devis gratuit.",
  url: "https://debarras-aurea.fr",

  contact: {
    phone: "+33 7 63 69 98 49",
    email: "contact@debarras-aurea.fr",
    address: "Île-de-France",
  },

  services: {
    particulier: {
      debarras: [
        {
          id: "debarras-maison",
          campaignGroup: "debarras_maison",
          campaignKey: "debarras_maison",
          intentKeywords: ["débarras maison", "vide maison", "vider maison", "débarrasser maison", "vidage maison"],
          negativeKeywords: ["mots fléchés", "jeu", "définition", "synonyme"],
          title: "Débarras maison (vide maison)",
          slug: "debarras-maison-vide-maison",
          icon: "home",
          description: "Débarras de maison en Île-de-France : vide maison complet, tri, évacuation et valorisation.",
          shortDescription: "Vider une maison rapidement, sans stress",
          features: ["Intervention rapide 24 à 48 h", "Tri sélectif", "Évacuation complète", "Devis gratuit"],
        },
        {
          id: "debarras-appartement",
          campaignGroup: "debarras_appartement",
          campaignKey: "debarras_appartement",
          intentKeywords: ["débarras appartement", "vide appartement", "vider appartement", "débarrasser appartement"],
          negativeKeywords: ["mots fléchés", "jeu", "définition", "synonyme"],
          title: "Débarras appartement (vide appartement)",
          slug: "debarras-appartement-vide-appartement",
          icon: "home",
          description: "Débarras d'appartement en Île-de-France : vide appartement, tri, évacuation et recyclage.",
          shortDescription: "Vider un appartement efficacement",
          features: ["Intervention rapide 24 à 48 h", "Tri sélectif", "Évacuation complète", "Devis gratuit"],
        },
        {
          id: "cave-grenier",
          campaignGroup: "debarras_stockage",
          campaignKey: "debarras_cave_grenier_garage",
          intentKeywords: ["débarras cave", "débarras grenier", "débarras garage", "vider cave", "vider grenier"],
          negativeKeywords: ["mots fléchés", "jeu", "définition", "vin", "aménagement"],
          title: "Garages, Caves et Greniers",
          slug: "debarras-cave-grenier",
          icon: "warehouse",
          description: "Évacuation de cave, grenier, garage et espaces encombrés",
          shortDescription: "Libérez vos espaces de stockage",
          features: ["Accès difficile", "Évacuation rapide", "Tri recyclable", "Prix compétitifs"],
        },
        {
          id: "succession",
          campaignGroup: "debarras_succession",
          campaignKey: "debarras_succession",
          intentKeywords: ["débarras succession", "vide maison décès", "débarras après décès", "succession débarras"],
          negativeKeywords: ["notaire", "avocat", "héritage impôt", "droits succession"],
          title: "Après Décès et Succession",
          slug: "debarras-succession",
          icon: "heart",
          description: "Accompagnement délicat dans le débarras après succession",
          shortDescription: "Service respectueux pour les moments difficiles",
          features: [
            "Accompagnement bienveillant",
            "Tri des objets de valeur",
            "Discrétion assurée",
            "Prise en charge administrative",
          ],
        },
        {
          id: "meubles",
          campaignGroup: "enlevement_encombrants",
          campaignKey: "enlevement_meubles_canapes",
          intentKeywords: ["enlèvement meubles", "débarras meubles", "enlèvement canapé", "enlever vieux meubles"],
          negativeKeywords: ["achat", "vente", "occasion", "ikea", "conforama"],
          title: "Meubles et Canapés",
          slug: "enlevement-meubles-canapes",
          icon: "armchair",
          description: "Enlèvement et évacuation de meubles encombrants",
          shortDescription: "Débarrassez-vous de vos vieux meubles",
          features: ["Démontage si nécessaire", "Transport sécurisé", "Recyclage", "Intervention express"],
        },
        {
          id: "electromenager",
          campaignGroup: "enlevement_encombrants",
          campaignKey: "enlevement_electromenager",
          intentKeywords: ["enlèvement électroménager", "débarras frigo", "enlever machine à laver", "recyclage électroménager"],
          negativeKeywords: ["achat", "réparation", "occasion", "neuf", "promotion"],
          title: "Électroménagers",
          slug: "enlevement-electromenager",
          icon: "microwave",
          description: "Récupération et recyclage d'appareils électroménagers",
          shortDescription: "Évacuation d'électroménager responsable",
          features: ["Recyclage DEEE", "Débranchement", "Évacuation sécurisée", "Gratuit selon volume"],
        },
        {
          id: "encombrants",
          campaignGroup: "enlevement_encombrants",
          campaignKey: "enlevement_encombrants",
          intentKeywords: ["enlèvement encombrants", "débarras encombrants", "ramassage encombrants", "jeter encombrants"],
          negativeKeywords: ["mairie", "calendrier", "jours collecte", "gratuit mairie"],
          title: "Encombrants Divers",
          slug: "enlevement-encombrants",
          icon: "package",
          description: "Collecte et évacuation de tous types d'encombrants",
          shortDescription: "Solution pour tous vos encombrants",
          features: ["Tous types d'objets", "Tri à la source", "Valorisation", "Intervention rapide"],
        },
        {
          id: "ecoresponsable",
          campaignGroup: "debarras_valorisation",
          campaignKey: "debarras_ecoresponsable",
          intentKeywords: ["débarras écologique", "débarras recyclage", "vide maison éco-responsable", "débarras gratuit don"],
          negativeKeywords: ["mots fléchés", "jeu", "définition"],
          title: "Débarras Éco-responsable",
          slug: "debarras-ecoresponsable",
          icon: "leaf",
          description: "Débarras avec valorisation maximale et recyclage",
          shortDescription: "Débarras respectueux de l'environnement",
          features: ["Tri sélectif", "Don aux associations", "Recyclage maximal", "Traçabilité"],
        },
      ],
      demenagement: [
        {
          id: "demenagement-particulier",
          campaignGroup: "demenagement_particulier",
          campaignKey: "demenagement_particulier",
          intentKeywords: ["déménagement particulier", "déménageur", "entreprise déménagement", "déménager"],
          negativeKeywords: ["gratuit", "seul", "sans déménageur", "location camion"],
          title: "Déménagement Particuliers",
          slug: "demenagement-particulier",
          icon: "truck",
          description: "Déménagement complet pour particuliers",
          shortDescription: "Déménagez en toute sérénité",
          features: ["Emballage", "Transport", "Déchargement", "Montage/démontage"],
        },
        {
          id: "transport-mobilier",
          campaignGroup: "devis_prix_demenagement",
          campaignKey: "transport_mobilier_objets_lourds",
          intentKeywords: ["transport meuble", "transport objet lourd", "transport piano", "livraison meuble"],
          negativeKeywords: ["gratuit", "location", "colissimo"],
          title: "Transport Mobilier et Objets Lourds",
          slug: "transport-mobilier-objets-lourds",
          icon: "package-check",
          description: "Transport sécurisé de meubles et objets volumineux",
          shortDescription: "Transport professionnel de gros volumes",
          features: ["Équipement adapté", "Personnel qualifié", "Assurance", "Protection des biens"],
        },
        {
          id: "demenagement-regional",
          campaignGroup: "demenagement_particulier",
          campaignKey: "demenagement_regional_national",
          intentKeywords: ["déménagement longue distance", "déménagement national", "déménagement régional", "déménager province"],
          negativeKeywords: ["gratuit", "international", "europe"],
          title: "Déménagements Nationaux et Régionaux",
          slug: "demenagement-national-regional",
          icon: "map",
          description: "Déménagement longue distance en France",
          shortDescription: "Déménagement dans toute la France",
          features: ["Toute France", "Planning flexible", "Suivi", "Devis détaillé"],
        },
        {
          id: "demenagement-express",
          campaignGroup: "demenagement_urgent",
          campaignKey: "demenagement_urgent",
          intentKeywords: ["déménagement urgent", "déménagement express", "déménagement rapide", "déménager vite"],
          negativeKeywords: ["gratuit", "seul"],
          title: "Déménagements Express et Urgents",
          slug: "demenagement-express-urgent",
          icon: "zap",
          description: "Service de déménagement en urgence",
          shortDescription: "Déménagement sous 24 à 48 h",
          features: ["24 à 48 h", "Disponibilité immédiate", "Organisation rapide", "Efficacité garantie"],
        },
        {
          id: "garde-meuble",
          campaignGroup: "garde_meuble",
          campaignKey: "garde_meuble",
          intentKeywords: ["garde meuble", "stockage meubles", "box stockage", "garde meuble particulier"],
          negativeKeywords: ["gratuit", "self storage"],
          title: "Garde-Meuble",
          slug: "garde-meuble",
          icon: "archive",
          description: "Stockage sécurisé de vos biens",
          shortDescription: "Solution de stockage flexible",
          features: ["Boxes sécurisés", "Accès 7j/7", "Toutes durées", "Surveillance 24h/24"],
        },
      ],
    },
    professionnel: {
      debarras: [
        {
          id: "bureaux-locaux",
          campaignGroup: "debarras_bureaux",
          campaignKey: "debarras_bureaux_locaux",
          intentKeywords: ["débarras bureaux", "vider bureau", "débarras local commercial", "vidage bureau"],
          negativeKeywords: ["meubles bureau achat", "location bureau"],
          title: "Bureaux et Locaux Commerciaux",
          slug: "debarras-bureaux-locaux",
          icon: "building-2",
          description: "Débarras professionnel de bureaux et locaux",
          shortDescription: "Vidage de locaux professionnels",
          features: ["Hors heures ouvrées", "Confidentialité", "Destruction documents", "Récupération matériel"],
        },
        {
          id: "commerces-entrepots",
          campaignGroup: "debarras_commerces",
          campaignKey: "debarras_commerces_entrepots",
          intentKeywords: ["débarras entrepôt", "débarras commerce", "vider entrepôt", "vidage local commercial"],
          negativeKeywords: ["location", "achat", "vente entrepôt"],
          title: "Commerces et Entrepôts",
          slug: "debarras-commerces-entrepots",
          icon: "store",
          description: "Évacuation de commerces et entrepôts",
          shortDescription: "Débarras de grands volumes",
          features: ["Gros volumes", "Matériel adapté", "Planning flexible", "Devis sur mesure"],
        },
        {
          id: "gravats",
          campaignGroup: "evacuation_gravats",
          campaignKey: "evacuation_gravats",
          intentKeywords: ["évacuation gravats", "enlèvement gravats", "déchets chantier", "benne gravats"],
          negativeKeywords: ["gratuit", "mairie", "déchèterie"],
          title: "Gravats et Déchets de Chantier",
          slug: "evacuation-gravats-dechets-chantier",
          icon: "hard-hat",
          description: "Évacuation de déchets de chantier",
          shortDescription: "Gestion des déchets professionnels",
          features: ["Toutes quantités", "Tri sélectif", "Bennes", "Certificats"],
        },
      ],
      demenagement: [
        {
          id: "demenagement-entreprise",
          campaignGroup: "demenagement_entreprise",
          campaignKey: "demenagement_entreprise",
          intentKeywords: ["déménagement entreprise", "déménagement bureau", "déménagement société", "déménageur professionnel"],
          negativeKeywords: ["particulier", "maison", "appartement"],
          title: "Déménagement d'Entreprises",
          slug: "demenagement-entreprise",
          icon: "briefcase",
          description: "Déménagement professionnel d'entreprise",
          shortDescription: "Déménagement sans interruption d'activité",
          features: ["Planning adapté", "Week-end/nuit", "IT et téléphonie", "Remise en service"],
        },
      ],
    },
  },

  zones: {
    departements: [
      { code: "75", name: "Paris" },
      { code: "77", name: "Seine-et-Marne" },
      { code: "78", name: "Yvelines" },
      { code: "91", name: "Essonne" },
      { code: "92", name: "Hauts-de-Seine" },
      { code: "93", name: "Seine-Saint-Denis" },
      { code: "94", name: "Val-de-Marne" },
      { code: "95", name: "Val-d'Oise" },
    ],
  },

  guarantees: [
    { text: "Intervention 24 à 48 h", subtext: "selon urgence" },
    { text: "Devis gratuit", subtext: "et sans engagement" },
    { text: "Tri et recyclage", subtext: "éco-responsable" },
  ],

  testimonials: [
    {
      name: "Marie D.",
      location: "Paris 15e",
      rating: 5,
      text: "Service impeccable pour le débarras de l'appartement de ma mère. L'équipe était professionnelle et respectueuse.",
      service: "Débarras d'appartement",
      date: "Il y a 2 semaines",
    },
    {
      name: "Jean-Pierre L.",
      location: "Versailles (78)",
      rating: 5,
      text: "Très satisfait du débarras de ma cave. Rapide, efficace et prix correct. Je recommande vivement.",
      service: "Débarras de cave",
      date: "Il y a 1 mois",
    },
    {
      name: "Sophie M.",
      location: "Créteil (94)",
      rating: 5,
      text: "Excellent accompagnement pour le débarras après succession. Un grand merci pour votre professionnalisme.",
      service: "Débarras succession",
      date: "Il y a 3 semaines",
    },
    {
      name: "Thomas B.",
      location: "Nanterre (92)",
      rating: 5,
      text: "Intervention express pour notre déménagement d'entreprise. Tout s'est passé parfaitement, aucune interruption d'activité.",
      service: "Déménagement entreprise",
      date: "Il y a 1 semaine",
    },
    {
      name: "Philippe K.",
      location: "Évry (91)",
      rating: 5,
      text: "Débarras de garage effectué en moins de 3 heures. Très bon rapport qualité-prix, je recommande sans hésiter.",
      service: "Débarras garage",
      date: "Il y a 5 jours",
    },
  ],

  faqs: [
    {
      category: "Général",
      questions: [
        {
          q: "Quels types de biens débarrassez-vous ?",
          a: "Nous débarrassons tous types d'objets et encombrants : meubles, électroménager, vêtements, livres, cartons, déchets verts... Nous excluons uniquement les matériaux dangereux (amiante, produits chimiques).",
        },
        {
          q: "Intervenez-vous le week-end ?",
          a: "Oui, nous intervenons 7 jours sur 7, y compris les week-ends et jours fériés, pour nous adapter à votre planning.",
        },
        {
          q: "Faut-il être présent pendant le débarras ?",
          a: "Non, ce n'est pas obligatoire. Nous sommes assurés et pouvons travailler avec un jeu de clés confié. Votre présence est toutefois recommandée pour toute validation spécifique.",
        },
        {
          q: "Êtes-vous assurés ?",
          a: "Oui, nous disposons d'une assurance responsabilité civile professionnelle complète qui couvre tous les risques pendant l'intervention.",
        },
        {
          q: "Combien coûte un débarras ?",
          a: "Le prix dépend du volume, de l'accessibilité et du type de biens à évacuer. Nous fournissons toujours un devis gratuit et détaillé après évaluation.",
        },
        {
          q: "Que faites-vous des objets en bon état ?",
          a: "Nous privilégions le don aux associations et le recyclage. Les objets valorisables sont triés et réemployés, seul le déchet ultime part en déchetterie.",
        },
      ],
    },
    {
      category: "Tarifs",
      questions: [
        {
          q: "Comment sont calculés vos tarifs ?",
          a: "Nos tarifs dépendent de plusieurs facteurs : volume à débarrasser, accessibilité (étage, ascenseur), type de biens, urgence de l'intervention. Nous fournissons toujours un devis gratuit et détaillé après évaluation.",
        },
        {
          q: "Y a-t-il des frais cachés ?",
          a: "Non, nos devis sont transparents et tout compris : main d'œuvre, transport, évacuation en déchetterie, tri et recyclage. Le prix indiqué est le prix final.",
        },
        {
          q: "Proposez-vous un rachat d'objets de valeur ?",
          a: "Oui, si des objets de valeur sont identifiés (meubles anciens, antiquités, etc.), nous pouvons les racheter ou les déduire du montant du devis. Notre expertise nous permet d'identifier ces pièces.",
        },
        {
          q: "Puis-je obtenir un devis sans visite ?",
          a: "Pour les petits volumes, un devis peut être établi sur photos. Pour les débarras complets, nous recommandons une visite gratuite pour évaluer précisément le volume et l'accessibilité.",
        },
      ],
    },
    {
      category: "Processus",
      questions: [
        {
          q: "Combien de temps prend un débarras ?",
          a: "Cela dépend du volume : un studio (2-3h), un appartement F3 (4-6h), une maison complète (1-2 jours). Nous vous indiquons la durée estimée dans le devis.",
        },
        {
          q: "Que faites-vous des objets récupérés ?",
          a: "Nous adoptons une démarche éco-responsable : les objets en bon état sont donnés à des associations (Emmaüs, Secours Populaire), les matériaux recyclables sont triés et valorisés, seul le déchet ultime part en déchetterie.",
        },
        {
          q: "Fournissez-vous un certificat de destruction ?",
          a: "Oui, nous pouvons fournir un certificat de destruction ou d'évacuation, particulièrement utile pour les professionnels, les syndics ou dans le cadre de successions.",
        },
      ],
    },
    {
      category: "Urgences",
      questions: [
        {
          q: "Pouvez-vous intervenir en urgence ?",
          a: "Oui, nous proposons un service d'intervention rapide sous 24 à 48 h selon votre urgence et nos disponibilités. Contactez-nous par téléphone pour une réponse immédiate.",
        },
        {
          q: "Intervenez-vous en cas d'encombrement extrême ?",
          a: "Oui, nous avons une équipe formée pour les situations délicates et les encombrements importants. Nous intervenons avec discrétion, respect et les équipements de protection adaptés.",
        },
      ],
    },
  ],

  process: [
    {
      step: 1,
      title: "Demande de devis",
      description: "Remplissez notre formulaire en ligne ou appelez-nous directement",
      icon: "phone",
    },
    {
      step: 2,
      title: "Évaluation",
      description: "Nous évaluons le volume et vous envoyons un devis gratuit sous 24h",
      icon: "clipboard",
    },
    {
      step: 3,
      title: "Planification",
      description: "Nous fixons ensemble la date et l'heure d'intervention",
      icon: "calendar",
    },
    {
      step: 4,
      title: "Intervention",
      description: "Notre équipe procède au débarras complet, tri et évacuation",
      icon: "check",
    },
  ],
} as const

export type ServiceCategory =
  | keyof typeof siteConfig.services.particulier
  | keyof typeof siteConfig.services.professionnel
